### ISSUE TITLE
Error while using PVC and helm

### ISSUE THREAD

**Issue by Abdulrahman-Hejazi** [hansehe/redisinsight-helm#1]
when I enable the volume storage the pod keeps crashing in a loop, however if I disable it, the pods works fine but I would need to connect it to redis in case of pod restart.

`# Default values for redisinsight.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true
replicaCount: 1

image:
  repository: redis/redisinsight
  pullPolicy: IfNotPresent
  versionOverride: "*"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: 10
environmentVariables: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 5540
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/probe-path: "/"
  headless:
    annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  hosts:
    - host: redisinsight.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: redisinsight-tls
  #    hosts:
  #      - redisinsight.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

volume:
  enabled: true
  className: "trk" 
  size: 1Gi
  annotations:
    helm.sh/resource-policy: "keep"

tests:
  enabled: false`

**Comment by hansehe** [comment]
Do you have the error logs to it? I'll try and check it out

**Comment by hansehe** [comment]
Hi again, the issue was related to the securityContext most likely, so check out the last commit with description on how to fix it.
In short, you have to enable these values:
```
securityContext: {}
  # Enable these permissions if you are running with a non-root user to allow for reading / writing to the volume
  # runAsUser: 1000
  # runAsGroup: 1000

initContainers: []
# Enable this to change the permissions of the volume to allow for reading / writing to the volume
# - name: redisinsight-init-permissions
#   image: busybox
#   command: ["sh", "-c", "chown -R 1000:1000 /data && chmod -R 775 /data"]
#   securityContext:
#     runAsUser: 0  # Run as root to ensure permissions can be changed
#   volumeMounts:
#     - mountPath: "/data"
#       name: redisinsight-volume
```

**Comment by Abdulrahman-Hejazi** [comment]
> Do you have the error logs to it? I'll try and check it out

unfortunately it didn't produce logs
